[package]
name = "simd-benches"
version = "0.0.0"
edition = "2021"
publish = false

[[bench]]
name = "uuid"
harness = false

[[bench]]
name = "hex"
harness = false

[[bench]]
name = "base64"
harness = false

[[bench]]
name = "base32"
harness = false

[[bench]]
name = "ascii"
harness = false

[[bench]]
name = "utf8"
harness = false

[[bench]]
name = "utf16"
harness = false

[dev-dependencies]
criterion = { version = "0.5.1", default-features = false, features = [
    "rayon",
] }

[dependencies]
base16 = "0.2.1"
base16ct = "0.2.0"
base32ct = "0.2.0"
base64 = "0.22.0"
base64ct = "1.6.0"
based64 = "0.4.5"
const-str = "0.5.3"
data-encoding = "2.3.3"
faster-hex = "0.9.0"
getrandom = { version = "0.2", features = ["js"] }
hex = "0.4.3"
radix64 = { version = "0.6.2", default-features = false }
rand = "0.8.5"
simdutf8 = "0.1.4"
simdutf = { git = "https://github.com/nathanwhit/simdutf-rs", branch = "base64" }
uuid = "1.3.0"
once_cell = "1.17.1"
bytemuck = "1.13.1"
widestring = "1.0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
encoding_rs = "0.8.34"

[dependencies.base32-simd]
git = "https://github.com/Nugine/simd.git"
rev = "77703beeb183844a15620fa3c427be02534b44bf"
default-features = false
features = ["std"]

[dependencies.base64-simd]
git = "https://github.com/Nugine/simd.git"
rev = "77703beeb183844a15620fa3c427be02534b44bf"
default-features = false
features = ["std"]

[dependencies.hex-simd]
git = "https://github.com/Nugine/simd.git"
rev = "77703beeb183844a15620fa3c427be02534b44bf"
default-features = false
features = ["std"]

[dependencies.unicode-simd]
git = "https://github.com/Nugine/simd.git"
rev = "77703beeb183844a15620fa3c427be02534b44bf"
default-features = false
features = ["std"]

[dependencies.uuid-simd]
git = "https://github.com/Nugine/simd.git"
rev = "77703beeb183844a15620fa3c427be02534b44bf"
default-features = false
features = ["std", "uuid"]

[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 1

[features]
default = []
detect = [
    "base32-simd/detect",
    "base64-simd/detect",
    "hex-simd/detect",
    "unicode-simd/detect",
    "uuid-simd/detect",
    "radix64/simd",        #
]
unstable = [
    "base32-simd/unstable",
    "base64-simd/unstable",
    "hex-simd/unstable",
    "unicode-simd/unstable",
    "uuid-simd/unstable",
    "criterion/real_blackbox",
    "encoding_rs/simd-accel",  #
]
parallel = ["base64-simd/parallel"]
